// All slugs below are verified against the Greenhouse public API.
// To add more: find the slug from boards.greenhouse.io/{slug} in their careers URL.

export const ATS_COMPANIES = [

  // ─── Greenhouse (verified working) ───────────────────────────────────────
  { name: 'Anthropic',          type: 'greenhouse', slug: 'anthropic' },
  { name: 'Stripe',             type: 'greenhouse', slug: 'stripe' },
  { name: 'Figma',              type: 'greenhouse', slug: 'figma' },
  { name: 'Airtable',           type: 'greenhouse', slug: 'airtable' },
  { name: 'Brex',               type: 'greenhouse', slug: 'brex' },
  { name: 'Coinbase',           type: 'greenhouse', slug: 'coinbase' },
  { name: 'Databricks',         type: 'greenhouse', slug: 'databricks' },
  { name: 'MongoDB',            type: 'greenhouse', slug: 'mongodb' },
  { name: 'Elastic',            type: 'greenhouse', slug: 'elastic' },
  { name: 'Grafana Labs',       type: 'greenhouse', slug: 'grafanalabs' },
  { name: 'HubSpot',            type: 'greenhouse', slug: 'hubspot' },
  { name: 'Twilio',             type: 'greenhouse', slug: 'twilio' },
  { name: 'Intercom',           type: 'greenhouse', slug: 'intercom' },
  { name: 'Asana',              type: 'greenhouse', slug: 'asana' },
  { name: 'Okta',               type: 'greenhouse', slug: 'okta' },
  { name: 'PagerDuty',          type: 'greenhouse', slug: 'pagerduty' },
  { name: 'Lyft',               type: 'greenhouse', slug: 'lyft' },
  { name: 'Instacart',          type: 'greenhouse', slug: 'instacart' },
  { name: 'Braze',              type: 'greenhouse', slug: 'braze' },
  { name: 'Amplitude',          type: 'greenhouse', slug: 'amplitude' },
  { name: 'LaunchDarkly',       type: 'greenhouse', slug: 'launchdarkly' },
  { name: 'InMobi',             type: 'greenhouse', slug: 'inmobi' },
  { name: 'Robinhood',          type: 'greenhouse', slug: 'robinhood' },
  { name: 'Faire',              type: 'greenhouse', slug: 'faire' },
  { name: 'Mixpanel',           type: 'greenhouse', slug: 'mixpanel' },
  { name: 'DataDog',            type: 'greenhouse', slug: 'datadog' },
  { name: 'Cloudflare',         type: 'greenhouse', slug: 'cloudflare' },
  { name: 'Twitch',             type: 'greenhouse', slug: 'twitch' },
  { name: 'Reddit',             type: 'greenhouse', slug: 'reddit' },
  { name: 'Pinterest',          type: 'greenhouse', slug: 'pinterest' },
  { name: 'Samsara',            type: 'greenhouse', slug: 'samsara' },
  { name: 'Gusto',              type: 'greenhouse', slug: 'gusto' },
  { name: 'Verkada',            type: 'greenhouse', slug: 'verkada' },
  { name: 'Abnormal Security',  type: 'greenhouse', slug: 'abnormalsecurity' },
  { name: 'Scale AI',           type: 'greenhouse', slug: 'scaleai' },
  { name: 'CoreWeave',          type: 'greenhouse', slug: 'coreweave' },
  { name: 'Airbnb',             type: 'greenhouse', slug: 'airbnb' },
  { name: 'Squarespace',        type: 'greenhouse', slug: 'squarespace' },
  { name: 'Dropbox',            type: 'greenhouse', slug: 'dropbox' },
  { name: 'Rubrik',             type: 'greenhouse', slug: 'rubrik' },
  { name: 'Netskope',           type: 'greenhouse', slug: 'netskope' },
]
