// Custom career pages — monitored by page-hash change detection.
// Add any URL here and the tracker will alert you when the page content changes.

export const URLS = [
  // ─── The startup you mentioned ───────────────────────────────────────────
  { name: 'Nulyft Tech',        url: 'https://nulyfttech.com/careers' },

  // ─── Indian Unicorns & Top Startups ──────────────────────────────────────
  { name: 'Razorpay',           url: 'https://razorpay.com/jobs/' },
  { name: 'PhonePe',            url: 'https://www.phonepe.com/careers/' },
  { name: 'CRED',               url: 'https://careers.cred.club/' },
  { name: 'Groww',              url: 'https://groww.in/jobs' },
  { name: 'Zepto',              url: 'https://www.zeptonow.com/careers' },
  { name: 'Meesho',             url: 'https://meesho.io/jobs' },
  { name: 'BrowserStack',       url: 'https://www.browserstack.com/careers' },
  { name: 'Postman',            url: 'https://www.postman.com/company/careers/' },
  { name: 'Zerodha',            url: 'https://zerodha.com/careers/' },
  { name: 'Slice',              url: 'https://www.sliceit.com/careers' },
  { name: 'Jupiter Money',      url: 'https://jupiter.money/careers/' },
  { name: 'Fi Money',           url: 'https://fi.money/careers' },
  { name: 'Khatabook',          url: 'https://khatabook.com/careers/' },
  { name: 'Urban Company',      url: 'https://careers.urbancompany.com/' },
  { name: 'Darwinbox',          url: 'https://darwinbox.com/en-in/company/careers' },
  { name: 'CleverTap',          url: 'https://clevertap.com/careers/' },
  { name: 'Chargebee',          url: 'https://www.chargebee.com/careers/' },
  { name: 'Freshworks',         url: 'https://careers.freshworks.com/' },
  { name: 'Dream11',            url: 'https://www.dream11.com/about/careers' },
  { name: 'MPL',                url: 'https://www.mpl.live/careers' },
  { name: 'Porter',             url: 'https://porter.in/careers' },
  { name: 'Rapido',             url: 'https://rapido.bike/careers/' },
  { name: 'Ditto Insurance',    url: 'https://joinditto.in/careers/' },
  { name: 'Smallcase',          url: 'https://smallcase.com/careers' },
  { name: 'Niyo',               url: 'https://goniyo.com/careers/' },
  { name: 'Open Financial',     url: 'https://open.money/careers' },
  { name: 'Springworks',        url: 'https://www.springworks.in/careers/' },
  { name: 'Setu',               url: 'https://setu.co/careers' },
  { name: 'Hasura',             url: 'https://hasura.io/careers/' },
  { name: 'Physics Wallah',     url: 'https://boards.greenhouse.io/physicswallah' },
  { name: 'Ather Energy',       url: 'https://atherenergy.com/careers' },
  { name: 'Lenskart',           url: 'https://www.lenskart.com/careers.html' },
  { name: 'Internshala',        url: 'https://internshala.com/about/careers' },
  { name: 'Recko',              url: 'https://recko.io/careers/' },

  // ─── Global companies with custom career pages ────────────────────────────
  { name: 'Notion',             url: 'https://www.notion.so/careers' },
  { name: 'Retool',             url: 'https://retool.com/careers' },
  { name: 'Vercel',             url: 'https://vercel.com/careers' },
  { name: 'Linear',             url: 'https://linear.app/careers' },
  { name: 'Supabase',           url: 'https://supabase.com/careers' },
  { name: 'Perplexity',         url: 'https://jobs.ashbyhq.com/perplexity-ai' },
  { name: 'Rippling',           url: 'https://www.rippling.com/careers' },
  { name: 'Miro',               url: 'https://miro.com/careers/' },
  { name: 'Ramp',               url: 'https://ramp.com/careers' },
  { name: 'Mercury',            url: 'https://mercury.com/about/careers' },
  { name: 'Deel',               url: 'https://www.deel.com/careers' },
  { name: 'Weights & Biases',   url: 'https://boards.greenhouse.io/wandb' },
  { name: 'Hugging Face',       url: 'https://apply.workable.com/huggingface/' },
  { name: 'PostHog',            url: 'https://posthog.com/careers' },
  { name: 'Raycast',            url: 'https://www.raycast.com/careers' },
  { name: 'Plaid',              url: 'https://plaid.com/careers/' },
  { name: 'Canva',              url: 'https://www.canva.com/careers/' },
  { name: 'Descript',           url: 'https://www.descript.com/careers' },
  { name: 'Coda',               url: 'https://coda.io/careers' },
]
